[build]
command = "cd frontend && bun run build"
publish = "frontend/dist"

[build.environment]

zNODE_VERSION = "20"
BUN_VERSION = "latest"

[site]
bucket = "frontend/dist"

# Cache everything by default
[[headers]]
for = "/*"
[headers.values]
Cache-Control = "public, max-age=3600"

# Don't cache HTML files
[[headers]]
for = "/*.html"
[headers.values]
Cache-Control = "no-cache"

# Cache static assets
[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable" 